# model structures to test
# modelA_driv: landward/seaward stable with all drivers
# modelA: landward/seaward stable with no drivers (will perturb variables directly)
# modelB: landward/seaward linked with no drivers (will perturb variables directly)
# modelB_driv: landward/seaward linked with all drivers

modelA_driv <- parse.digraph(c('LandwardLatAccom->LandwardPropag',
                'LandwardPropag->LandwardMang',
                'LandwardMang->OM',
                'LandwardMang-*LandwardMang',
                'LandwardPropag-*LandwardPropag',
                'SeawardLatAccom->SeawardPropag',
                'SeawardPropag->SeawardMang',
                'SeawardMang->OM',
                'SeawardMang-*SeawardMang',
                'SeawardPropag-*SeawardPropag',
                #'LandwardLatAccom-*SeawardLatAccom',
                #'SeawardLatAccom-*LandwardLatAccom',
                #'LandwardPropag-*SeawardPropag',
                #'SeawardPropag-*LandwardPropag',
                #'LandwardMang-*SeawardMang',
                #'SeawardMang-*LandwardMang',
                'SeaLevelFall-*LandwardLatAccom',
                'SeaLevelFall-*LandwardMang',
                'SeaLevelFall->SeawardLatAccom',
                'SeaLevelRise->LandwardLatAccom',
                'SeaLevelRise-*SeawardMang',
                'SeaLevelRise->SeawardLatAccom',
                'Cyclones-*LandwardMang',
                'Cyclones->SeawardMang',
                'Restoration->LandwardPropag',
                'Restoration->SeawardPropag',
                'TidalAmp->LandwardLatAccom',
                'TidalAmp->SeawardLatAccom',
                'BasementUp-*LandwardLatAccom',
                'BasementUp-*LandwardMang',
                'BasementUp->SeawardLatAccom',
                'Subsidence->LandwardLatAccom',
                'Subsidence-*SeawardMang',
                'Subsidence-*SeawardLatAccom',
                'CoastalDev-*LandwardLatAccom',
                'CoastalDev-*LandwardMang',
                'CoastalDev-*SeawardMang',
                'Protection-*CoastalDev',
                'Erosion-*SeawardMang',
                'PermeableDam-*Erosion',
                'HydroEnergy->Erosion',
                'OM->SubVol',
                'TidalFreq-*SeawardPropag',
                'TidalFreq-*SubVol',
                'SubVol->SeawardLatAccom',
                'Autocompaction-*SubVol',
                'SedSupply-*SubVol',
                'Dams-*SedSupply',
                'HydroEnergy-*SeawardLatAccom',
                'HydroEnergy-*SeawardPropag'
))
modelA_driv <- enforce.limitation(modelA_driv)

modelB_driv <- parse.digraph(c('LandwardLatAccom->LandwardPropag',
                               'LandwardPropag->LandwardMang',
                               'LandwardMang->OM',
                               'LandwardMang-*LandwardMang',
                               'LandwardPropag-*LandwardPropag',
                               'SeawardLatAccom->SeawardPropag',
                               'SeawardPropag->SeawardMang',
                               'SeawardMang->OM',
                               'SeawardMang-*SeawardMang',
                               'SeawardPropag-*SeawardPropag',
                               'LandwardLatAccom-*SeawardLatAccom',
                               'SeawardLatAccom-*LandwardLatAccom',
                               'LandwardPropag-*SeawardPropag',
                               'SeawardPropag-*LandwardPropag',
                               'LandwardMang-*SeawardMang',
                               'SeawardMang-*LandwardMang',
                               'SeaLevelFall-*LandwardLatAccom',
                               'SeaLevelFall-*LandwardMang',
                               'SeaLevelFall->SeawardLatAccom',
                               'SeaLevelRise->LandwardLatAccom',
                               'SeaLevelRise-*SeawardMang',
                               'SeaLevelRise->SeawardLatAccom',
                               'Cyclones-*LandwardMang',
                               'Cyclones->SeawardMang',
                               'Restoration->LandwardPropag',
                               'Restoration->SeawardPropag',
                               'TidalAmp->LandwardLatAccom',
                               'TidalAmp->SeawardLatAccom',
                               'BasementUp-*LandwardLatAccom',
                               'BasementUp-*LandwardMang',
                               'BasementUp->SeawardLatAccom',
                               'Subsidence->LandwardLatAccom',
                               'Subsidence-*SeawardMang',
                               'Subsidence-*SeawardLatAccom',
                               'CoastalDev-*LandwardLatAccom',
                               'CoastalDev-*LandwardMang',
                               'CoastalDev-*SeawardMang',
                               'Protection-*CoastalDev',
                               'Erosion-*SeawardMang',
                               'PermeableDam-*Erosion',
                               'HydroEnergy->Erosion',
                               'OM->SubVol',
                               'TidalFreq-*SeawardPropag',
                               'TidalFreq-*SubVol',
                               'SubVol->SeawardLatAccom',
                               'Autocompaction-*SubVol',
                               'SedSupply-*SubVol',
                               'Dams-*SedSupply',
                               'HydroEnergy-*SeawardLatAccom',
                               'HydroEnergy-*SeawardPropag'
))
modelB_driv <- enforce.limitation(modelB_driv)

modelA <- parse.digraph(c('LandwardLatAccom->LandwardPropag',
                               'LandwardPropag->LandwardMang',
                               'LandwardMang->OM',
                               #'LandwardMang-*LandwardMang',
                               #'LandwardPropag-*LandwardPropag',
                               'SeawardLatAccom->SeawardPropag',
                               'SeawardPropag->SeawardMang',
                               'SeawardMang->OM',
                               #'SeawardMang-*SeawardMang',
                               #'SeawardPropag-*SeawardPropag',
                               #'LandwardLatAccom-*SeawardLatAccom',
                               #'SeawardLatAccom-*LandwardLatAccom',
                               #'LandwardPropag-*SeawardPropag',
                               #'SeawardPropag-*LandwardPropag',
                               #'LandwardMang-*SeawardMang',
                               #'SeawardMang-*LandwardMang',
                               'OM->SubVol',
                               'SubVol->SeawardLatAccom'
))
modelA <- enforce.limitation(modelA)

modelAsimp <- parse.digraph(c('LandwardLatAccom->LandwardMang',
                          'LandwardMang->OM',
                          #'LandwardMang-*LandwardMang',
                          #'LandwardPropag-*LandwardPropag',
                          'SeawardLatAccom->SeawardMang',
                          #'SeawardPropag->SeawardMang',
                          'SeawardMang->OM',
                          #'SeawardMang-*SeawardMang',
                          #'SeawardPropag-*SeawardPropag',
                          #'LandwardLatAccom-*SeawardLatAccom',
                          #'SeawardLatAccom-*LandwardLatAccom',
                          #'LandwardPropag-*SeawardPropag',
                          #'SeawardPropag-*LandwardPropag',
                          #'LandwardMang-*SeawardMang',
                          #'SeawardMang-*LandwardMang',
                          'OM->SubVol',
                          'SubVol->SeawardLatAccom'
))
modelAsimp <- enforce.limitation(modelAsimp)

modelB <- parse.digraph(c('LandwardLatAccom->LandwardPropag',
                               'LandwardPropag->LandwardMang',
                               'LandwardMang->OM',
                               'LandwardMang-*LandwardMang',
                               'LandwardPropag-*LandwardPropag',
                               'SeawardLatAccom->SeawardPropag',
                               'SeawardPropag->SeawardMang',
                               'SeawardMang->OM',
                               'SeawardMang-*SeawardMang',
                               'SeawardPropag-*SeawardPropag',
                               'LandwardLatAccom-*SeawardLatAccom',
                               'SeawardLatAccom-*LandwardLatAccom',
                               'LandwardPropag-*SeawardPropag',
                               'SeawardPropag-*LandwardPropag',
                               'LandwardMang-*SeawardMang',
                               'SeawardMang-*LandwardMang',
                               'OM->SubVol',
                               'SubVol->SeawardLatAccom'
))
modelB <- enforce.limitation(modelB)
