library(QPress)
library(dagitty)
library(ggdag)
library(igraph)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)

# build model signed digraphs

# mangrove system + local factors + anthropogenic pressures + climate pressures
modelB <- parse.digraph(c(#'LandwardEstabSpace->LandwardPropag',
                          #'LandwardPropag->LandwardMang',
                          'LandwardMang->SubVol',
                          #'SeawardEstabSpace->SeawardPropag',
                          #'SeawardPropag->SeawardMang',
                          'SeawardMang<->SubVol',
                          #'OM->SubVol',
                          #'SubVol->SeawardMang', 
                          'LandwardAvailableProp->LandwardMang',
                          'SeawardAvailableProp->SeawardMang',
                          #'AccommSpace->LandwardEstabSpace',
                          #'AccommSpace->SeawardEstabSpace',
                          #'HydroEnergy-*SeawardEstabSpace',
                          #'HydroEnergy->Erosion',
                          'Erosion-*SubVol',
                          #'Erosion-*SeawardPropag',
                          'Erosion-*SeawardMang',
                          'Precipitation->Sediment',
                          'Dams-*Sediment',
                          'Sediment->SubVol',
                          #'Autocompaction-*SubVol',
                          #'TidalFreq-*SeawardPropag',
                          #'TidalFreq->SubVol',
                          #'CoastalDev-*LandwardEstabSpace',
                          #'CoastalDev-*LandwardPropag',
                          'CoastalDev-*LandwardMang',
                          'CoastalDev--*SeawardMang',
                          #'CoastalDev--*SeawardPropag',
                          'GroundSubsid->LandwardMang',
                          #'GroundSubsid-*SeawardEstabSpace',
                          #'GroundSubsid-*SeawardPropag',
                          'GroundSubsid-*SeawardMang',
                          'SeaLevelRise->LandwardMang',
                          #'SeaLevelRise-*SeawardEstabSpace',
                          #'SeaLevelRise-*SeawardPropag',
                          'SeaLevelRise-*SeawardMang',
                          #'Cyclones--*LandwardPropag',
                          'Cyclones--*LandwardMang',
                          'Cyclones-*SeawardMang',
                          #'Cyclones-*SeawardPropag',
                          'Cyclones-*SubVol',
                          'Cyclones-->LandwardAvailableProp',
                          'Drought-*Sediment'
)) %>% 
  enforce.limitation()

grViz(grviz.digraph(modelB)) %>%
  export_svg %>% charToRaw %>% rsvg_png("outputs/modelB_signed-digraph.png")

# mangrove model where cyclones increase sub volume
modelB.1 <- parse.digraph(c(#'LandwardEstabSpace->LandwardPropag',
  #'LandwardPropag->LandwardMang',
  'LandwardMang->SubVol',
  #'SeawardEstabSpace->SeawardPropag',
  #'SeawardPropag->SeawardMang',
  'SeawardMang<->SubVol',
  #'OM->SubVol',
  #'SubVol->SeawardMang', 
  'LandwardAvailableProp->LandwardMang',
  'SeawardAvailableProp->SeawardMang',
  #'AccommSpace->LandwardEstabSpace',
  #'AccommSpace->SeawardEstabSpace',
  #'HydroEnergy-*SeawardEstabSpace',
  #'HydroEnergy->Erosion',
  'Erosion-*SubVol',
  #'Erosion-*SeawardPropag',
  'Erosion-*SeawardMang',
  'Precipitation->Sediment',
  'Dams-*Sediment',
  'Sediment->SubVol',
  #'Autocompaction-*SubVol',
  #'TidalFreq-*SeawardPropag',
  #'TidalFreq->SubVol',
  #'CoastalDev-*LandwardEstabSpace',
  #'CoastalDev-*LandwardPropag',
  'CoastalDev-*LandwardMang',
  'CoastalDev--*SeawardMang',
  #'CoastalDev--*SeawardPropag',
  'GroundSubsid->LandwardMang',
  #'GroundSubsid-*SeawardEstabSpace',
  #'GroundSubsid-*SeawardPropag',
  'GroundSubsid-*SeawardMang',
  'SeaLevelRise->LandwardMang',
  #'SeaLevelRise-*SeawardEstabSpace',
  #'SeaLevelRise-*SeawardPropag',
  'SeaLevelRise-*SeawardMang',
  #'Cyclones--*LandwardPropag',
  'Cyclones--*LandwardMang',
  'Cyclones-*SeawardMang',
  #'Cyclones-*SeawardPropag',
  'Cyclones->SubVol',
  'Cyclones-->LandwardAvailableProp',
  'Drought-*Sediment'
)) %>% 
  enforce.limitation()

# where not all variables have density depdenence

# mangrove system + local factors + anthropogenic pressures + climate pressures
modelB.2 <- parse.digraph(c(#'LandwardEstabSpace->LandwardPropag',
  #'LandwardPropag->LandwardMang',
  'LandwardMang->SubVol',
  #'SeawardEstabSpace->SeawardPropag',
  #'SeawardPropag->SeawardMang',
  'SeawardMang<->SubVol',
  #'OM->SubVol',
  #'SubVol->SeawardMang', 
  'LandwardAvailableProp->LandwardMang',
  'SeawardAvailableProp->SeawardMang',
  #'AccommSpace->LandwardEstabSpace',
  #'AccommSpace->SeawardEstabSpace',
  #'HydroEnergy-*SeawardEstabSpace',
  #'HydroEnergy->Erosion',
  'Erosion-*SubVol',
  #'Erosion-*SeawardPropag',
  'Erosion-*SeawardMang',
  'Precipitation->Sediment',
  'Dams-*Sediment',
  'Sediment->SubVol',
  #'Autocompaction-*SubVol',
  #'TidalFreq-*SeawardPropag',
  #'TidalFreq->SubVol',
  #'CoastalDev-*LandwardEstabSpace',
  #'CoastalDev-*LandwardPropag',
  'CoastalDev-*LandwardMang',
  'CoastalDev--*SeawardMang',
  #'CoastalDev--*SeawardPropag',
  'GroundSubsid->LandwardMang',
  #'GroundSubsid-*SeawardEstabSpace',
  #'GroundSubsid-*SeawardPropag',
  'GroundSubsid-*SeawardMang',
  'SeaLevelRise->LandwardMang',
  #'SeaLevelRise-*SeawardEstabSpace',
  #'SeaLevelRise-*SeawardPropag',
  'SeaLevelRise-*SeawardMang',
  #'Cyclones--*LandwardPropag',
  'Cyclones--*LandwardMang',
  'Cyclones-*SeawardMang',
  #'Cyclones-*SeawardPropag',
  'Cyclones-*SubVol',
  'Cyclones-->LandwardAvailableProp',
  'Drought-*Sediment',
  'LandwardMang-*LandwardMang',
  'SeawardMang-*SeawardMang',
  'SubVol-*SubVol',
  'Dams-*Dams',
  'CoastalDev-*CoastalDev',
  'Sediment-*Sediment',
  'LandwardAvailableProp-*LandwardAvailableProp',
  'SeawardAvailableProp-*SeawardAvailableProp',
  'Cyclones-*Cyclones',
  'GroundSubsid-*GroundSubsid',
  'Erosion-*Erosion',
  'Drought-*Drought',
  'Precipitation-*Precipitation'
)) #%>% 
  #enforce.limitation()


# mangrove system + local factors + anthropogenic pressures + climate pressures
modelA <- parse.digraph(c('LandwardEstabSpace->LandwardPropag',
                          'LandwardPropag->LandwardMang',
                          'LandwardMang->OM',
                          'SeawardEstabSpace->SeawardPropag',
                          'SeawardPropag->SeawardMang',
                          'SeawardMang->OM',
                          'OM->SubVol',
                          'SubVol->SeawardEstabSpace', 
                          'LandwardAvailableProp->LandwardPropag',
                          'SeawardAvailableProp->SeawardPropag',
                          #'AccommSpace->LandwardEstabSpace',
                          #'AccommSpace->SeawardEstabSpace',
                          #'HydroEnergy-*SeawardEstabSpace',
                          #'HydroEnergy->Erosion',
                          'Erosion-*SubVol',
                          'Erosion-*SeawardPropag',
                          'Erosion-*SeawardMang',
                          #'Precipitation->Sediment',
                          'Dams-*Sediment',
                          'Sediment->SubVol',
                          #'Autocompaction-*SubVol',
                          #'TidalFreq-*SeawardPropag',
                          #'TidalFreq->SubVol',
                          'CoastalDev-*LandwardEstabSpace',
                          'CoastalDev-*LandwardPropag',
                          'CoastalDev-*LandwardMang',
                          'CoastalDev--*SeawardMang',
                          'CoastalDev--*SeawardPropag',
                          'GroundSubsid->LandwardEstabSpace',
                          'GroundSubsid-*SeawardEstabSpace',
                          'GroundSubsid-*SeawardPropag',
                          'GroundSubsid-*SeawardMang',
                          'SeaLevelRise->LandwardEstabSpace',
                          'SeaLevelRise-*SeawardEstabSpace',
                          'SeaLevelRise-*SeawardPropag',
                          'SeaLevelRise-*SeawardMang',
                          'Cyclones--*LandwardPropag',
                          'Cyclones--*LandwardMang',
                          'Cyclones-*SeawardMang',
                          'Cyclones-*SeawardPropag',
                          'Cyclones-*SubVol',
                          'Cyclones-->LandwardAvailableProp'
)) %>% 
  enforce.limitation()

grViz(grviz.digraph(modelA)) %>%
export_svg %>% charToRaw %>% rsvg_png("outputs/modelA_signed-digraph.png")
